sudo: true
language: python
python:
  - "2.7"

services:
  - mysql


before_script:
- mkdir -p /tmp/logs
- mysql -uroot -e 'create database if not exists test;'
- mysql -uroot test < tests/date_test.sql


# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script:
  - coverage run app/operator.py
  - pytest tests/test_mysql_app.py

notifications:
  slack: yumimobi:L3GWHNFixRYLWBiPM6nZ82Hp # myself
#  slack: yumimobi:SJROQPkCaiM9JZQgIsMUCvWK # data